use pixors_shader_macro::kernel;

#[kernel(
    source   = "shaders/color.slang",
    entry    = "cs_cc",
    body_fn  = "cs_cc",
    includes("shaders"),
    specialize(U8Codec, U8Codec),
    specialize(U8Codec, U16Codec),
    specialize(U8Codec, F16Codec),
    specialize(U8Codec, F32Codec),
    specialize(U16Codec, U8Codec),
    specialize(U16Codec, U16Codec),
    specialize(U16Codec, F16Codec),
    specialize(U16Codec, F32Codec),
    specialize(F16Codec, U8Codec),
    specialize(F16Codec, U16Codec),
    specialize(F16Codec, F16Codec),
    specialize(F16Codec, F32Codec),
    specialize(F32Codec, U8Codec),
    specialize(F32Codec, U16Codec),
    specialize(F32Codec, F16Codec),
    specialize(F32Codec, F32Codec),
    inputs(src),
    output = "dst",
    workgroup(8, 8, 1),
    dispatch(PerPixel),
    class(PerPixel),
)]
#[repr(C)]
pub struct ColorConvertParams {
    pub width: u32,
    pub height: u32,
    pub transfer_src: u32,
    pub transfer_dst: u32,
    pub m00: f32,
    pub m01: f32,
    pub m02: f32,
    pub _p0: f32,
    pub m10: f32,
    pub m11: f32,
    pub m12: f32,
    pub _p1: f32,
    pub m20: f32,
    pub m21: f32,
    pub m22: f32,
    pub _p2: f32,
    pub alpha_policy_src: u32,
    pub alpha_policy_dst: u32,
    pub model_transform: u32,
    pub src_channels: u32,
    pub dst_channels: u32,
}
